import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import '../styles/Test.css'
import '../styles/PostTest.css'

function PostTest({ language, username }) {
  const navigate = useNavigate()
  const isZh = language === 'zh'
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  const [form, setForm] = useState({
    // Experience of Stratux (11 questions, 5-point Likert scale)
    q1_continuousEngage: '', // Q1: During the classroom learning session, I was naturally inclined to continuously engage in dialogue
    q2_challengeAppropriate: '', // Q2: In the classroom-based assessment, I found the level of challenge to be appropriate
    q3_clearFlow: '', // Q3: The overall classroom flow and instructional structure were clear
    q4_distinguishRoles: '', // Q4: I was able to clearly distinguish the functional differences among the various AI roles
    q5_teacherEffective: '', // Q5: The AI Teacher effectively explained concepts and addressed my questions
    q6_peerEngaged: '', // Q6: The AI Peer engaged in discussions with me by proposing new ideas
    q7_evaluatorsHelpful: '', // Q7: The ratings and feedback summaries provided by the three AI Evaluators supported my understanding
    q8_communicateMoreWithTeacher: '', // Q8: I tended to communicate more frequently with the AI Teacher role than with the AI Peer role
    q9_reasonableCredible: '', // Q9: I consider the questions, feedback, and scores generated by the AI system to be reasonable and credible
    q10_aiHallucinations: '', // Q10: During the learning process, I noticed instances of AI hallucinations
    q11_effortDirection: '50', // Q11: Effort direction slider (0-100, where 0 = (a) and 100 = (b))
    
    // Prior knowledge
    q12_sameTopic: '', // Is the topic you learned in Stratux the same as that you learned using DeepSeek before?
    q12_differentTopic: '', // If not, what did you learn?
    q13_familiarity: '', // Before this study session, how would you rate your familiarity with the learning topic? (0-5)
    q14_difficulty: '', // In your perspective, how would you rate the overall difficulty of this learning topic? (1-5)
    
    // Task Load Assessment (NASA Task Load Index) - 6 questions
    q15_mentalEffort: '', // Mental effort and attention required
    q16_physicalEffort: '', // Physical effort required
    q17_timePressure: '', // Time pressure experienced
    q18_overallEffort: '', // Overall effort required
    q19_satisfaction: '', // Satisfaction with own performance
    q20_frustration: '', // Frustration, tension, or irritation experienced
    
    // Open-ended Questions
    q21_mostHelpfulBloom: '', // Which level of Bloom's Taxonomy was most helpful?
    q22_leastHelpfulBloom: '', // Which level of Bloom's Taxonomy was least helpful?
    q23_mostBeneficialRole: '', // Which AI role did you find most beneficial?
    q24_additionalComments: '' // Additional comments, suggestions, or feedback
  })

  const handleChange = (field, value) => {
    setForm(prev => ({ ...prev, [field]: value }))
  }

  const handleSubmit = async () => {
    // Validate required questions
    const missingFields = []
    
    // Experience of Stratux (Q1-Q11)
    const experienceQuestions = [
      { key: 'q1_continuousEngage', label: isZh ? '持续参与对话' : 'Continuous engagement' },
      { key: 'q2_challengeAppropriate', label: isZh ? '挑战适当性' : 'Challenge appropriateness' },
      { key: 'q3_clearFlow', label: isZh ? '流程清晰度' : 'Clear flow' },
      { key: 'q4_distinguishRoles', label: isZh ? '区分角色差异' : 'Distinguish roles' },
      { key: 'q5_teacherEffective', label: isZh ? 'AI教师有效性' : 'AI Teacher effectiveness' },
      { key: 'q6_peerEngaged', label: isZh ? 'AI同伴参与度' : 'AI Peer engagement' },
      { key: 'q7_evaluatorsHelpful', label: isZh ? '评估者帮助性' : 'Evaluators helpfulness' },
      { key: 'q8_communicateMoreWithTeacher', label: isZh ? '与教师交流频率' : 'Communication with teacher' },
      { key: 'q9_reasonableCredible', label: isZh ? '合理性和可信度' : 'Reasonableness and credibility' },
      { key: 'q10_aiHallucinations', label: isZh ? 'AI幻觉' : 'AI hallucinations' },
      { key: 'q11_effortDirection', label: isZh ? '努力方向' : 'Effort direction' }
    ]
    
    const missingExperience = experienceQuestions.filter(q => !form[q.key] || form[q.key] === '')
    if (missingExperience.length > 0) {
      missingFields.push(isZh ? 'Stratux体验问题' : 'Experience of Stratux questions')
    }
    
    // Prior knowledge
    if (!form.q12_sameTopic) {
      missingFields.push(isZh ? '是否相同主题' : 'Same topic question')
    }
    
    if (form.q12_sameTopic === 'no' && (!form.q12_differentTopic || !form.q12_differentTopic.trim())) {
      missingFields.push(isZh ? '不同主题说明' : 'Different topic explanation')
    }
    
    if (form.q13_familiarity === '') {
      missingFields.push(isZh ? '熟悉程度评分' : 'Familiarity rating')
    }
    
    if (!form.q14_difficulty) {
      missingFields.push(isZh ? '难度评分' : 'Difficulty rating')
    }
    
    // Task Load Assessment
    const nasaQuestions = [
      { key: 'q15_mentalEffort', label: isZh ? '心理努力' : 'Mental effort' },
      { key: 'q16_physicalEffort', label: isZh ? '身体努力' : 'Physical effort' },
      { key: 'q17_timePressure', label: isZh ? '时间压力' : 'Time pressure' },
      { key: 'q18_overallEffort', label: isZh ? '总体努力' : 'Overall effort' },
      { key: 'q19_satisfaction', label: isZh ? '满意度' : 'Satisfaction' },
      { key: 'q20_frustration', label: isZh ? '挫败感' : 'Frustration' }
    ]
    
    const missingNASA = nasaQuestions.filter(q => !form[q.key])
    if (missingNASA.length > 0) {
      missingFields.push(isZh ? '任务负荷评估问题' : 'Task Load Assessment questions')
    }
    
    if (missingFields.length > 0) {
      const message = isZh 
        ? `请完成以下必答问题：${missingFields.join('、')}`
        : `Please complete the following required questions: ${missingFields.join(', ')}`
      alert(message)
      return
    }
    
    // All required questions answered, save questionnaire
    setSubmitting(true)
    setError('')
    
    try {
      const response = await fetch('/api/save-posttest', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          username: username || null,
          language: language || null,
          responses: form
        })
      })
      
      if (!response.ok) {
        const text = await response.text()
        console.error('Failed to save posttest:', text)
        throw new Error(isZh ? '保存问卷失败，请稍后重试。' : 'Failed to save questionnaire. Please try again later.')
      }
      
      // Save successful, clear language and username, return to language selection
      try {
        localStorage.removeItem('app_language')
        localStorage.removeItem('app_username')
      } catch (e) {
        console.warn('Failed to clear localStorage language/user:', e)
      }
      // Use full refresh to ensure return to language selection and reset state
      window.location.href = '/'
    } catch (err) {
      console.error('PostTest submit error:', err)
      setError(err.message || (isZh ? '提交失败，请稍后重试。' : 'Submit failed. Please try again.'))
      setSubmitting(false)
    }
  }

  return (
    <div className={`test-container posttest-container ${!isZh ? 'lang-en' : ''}`} lang={language}>
      <header className="test-top-bar">
        <div>
          <h1>{isZh ? '后测问卷' : 'Post-Test Questionnaire'}</h1>
          <p>
            {isZh
              ? '感谢您完成Stratux教室体验，请回答以下问题，帮助我们了解您的体验和感受。'
              : 'Thank you for completing your Stratux classroom experience. Please answer the following questions to help us understand your experience and feedback.'}
          </p>
        </div>
        <div className="test-top-actions">
          <button 
            className="test-end-btn" 
            onClick={handleSubmit}
            disabled={submitting}
          >
            {submitting 
              ? (isZh ? '提交中…' : 'Submitting…')
              : (isZh ? '提交问卷' : 'Submit Questionnaire')}
          </button>
        </div>
      </header>

      <div className="test-main pretest-main">
        <form className="pretest-form-wrapper">
          <section className="test-panel pretest-panel pretest-panel-left">
            <div className="test-chat-feed pretest-form">
              <div className="pretest-topic-header">
                <h3>{isZh ? 'Stratux体验' : 'Experience of Stratux'}</h3>
                <p className="pretest-topic-intro">
                  {isZh
                    ? '请根据您在Stratux系统中的学习体验，对以下陈述表示您的同意程度。回答采用5点李克特量表（1 = 强烈不同意，5 = 强烈同意）。'
                    : 'Please indicate your level of agreement with the following statements based on your learning experience with the Stratux system. Responses are measured on a 5-point Likert scale (1 = Strongly Disagree, 5 = Strongly Agree).'}
                </p>
                <div className="pretest-topic-divider"></div>
              </div>

              {[
                { 
                  id: 'q1_continuousEngage',
                  num: 1,
                  text: isZh
                    ? '在课堂学习过程中，我自然地倾向于持续与AI进行对话并尝试回答它的问题。'
                    : 'During the classroom learning session, I was naturally inclined to continuously engage in dialogue with the AI and attempt to respond to its questions.'
                },
                {
                  id: 'q2_challengeAppropriate',
                  num: 2,
                  text: isZh 
                    ? '在基于课堂的评估中，我发现挑战水平适当，反馈精确有效，帮助我识别理解上的差距。'
                    : 'In the classroom-based assessment, I found the level of challenge to be appropriate, and the feedback to be precise and effective in helping me identify gaps in my understanding.'
                },
                { 
                  id: 'q3_clearFlow',
                  num: 3,
                  text: isZh 
                    ? '整体课堂流程和教学结构清晰易懂，我在学习过程中没有感到过度困惑或迷失方向。'
                    : 'The overall classroom flow and instructional structure were clear and easy to follow, and I did not feel excessively confused or disoriented during the learning process.'
                },
                { 
                  id: 'q4_distinguishRoles',
                  num: 4,
                  text: isZh 
                    ? '我能够清楚地区分各种AI角色（例如：教师、同伴、考官、评估者）的功能差异。'
                    : 'I was able to clearly distinguish the functional differences among the various AI roles (e.g., Teacher, Peer, Examiner, Evaluator).'
                },
                { 
                  id: 'q5_teacherEffective',
                  num: 5,
                  text: isZh 
                    ? 'AI教师在学习过程中有效地解释概念并回答我的问题。'
                    : 'The AI Teacher effectively explained concepts and addressed my questions during the learning process.'
                },
                {
                  id: 'q6_peerEngaged',
                  num: 6,
                  text: isZh 
                    ? 'AI同伴通过提出新想法或提出相关问题与我进行讨论。'
                    : 'The AI Peer engaged in discussions with me by proposing new ideas or raising relevant questions.'
                },
                { 
                  id: 'q7_evaluatorsHelpful',
                  num: 7,
                  text: isZh 
                    ? '三位AI评估者提供的评分和反馈总结支持我了解自己的学习状态，并帮助我补充缺失的知识。'
                    : 'The ratings and feedback summaries provided by the three AI Evaluators supported my understanding of my learning status and helped me supplement missing knowledge.'
                },
                { 
                  id: 'q8_communicateMoreWithTeacher',
                  num: 8,
                  text: isZh 
                    ? '我倾向于与AI教师角色交流的频率高于与AI同伴角色。'
                    : 'I tended to communicate more frequently with the AI Teacher role than with the AI Peer role.'
                },
                { 
                  id: 'q9_reasonableCredible',
                  num: 9,
                  text: isZh 
                    ? '我认为AI系统生成的问题、反馈和分数是合理且可信的。'
                    : 'I consider the questions, feedback, and scores generated by the AI system to be reasonable and credible.'
                },
                { 
                  id: 'q10_aiHallucinations',
                  num: 10,
                  text: isZh 
                    ? '在学习过程中，我注意到AI幻觉（即不正确或事实不准确的回答）或上下文错误的情况，这降低了我对AI系统的信任度。'
                    : 'During the learning process, I noticed instances of AI hallucinations (i.e., incorrect or factually inaccurate responses) or contextual errors, which reduced my level of trust in the AI system.'
                },
                { 
                  id: 'q11_effortDirection',
                  num: 11,
                  text: isZh 
                    ? '在您的体验中，与AI交互所花费的努力是倾向于（a）主动思考和完成任务，还是（b）费力地试图理解和猜测AI的意图和答案？'
                    : 'In your experience, the effort spent interacting with AI is directed towards (a) proactively thinking and completing tasks, or (b) towards painstakingly trying to understand and guess the AI\'s intentions and answers.'
                }
              ].map(item => {
                if (item.id === 'q11_effortDirection') {
                  // Special handling for slider question
                  return (
                    <div key={item.id} className="pretest-question">
                      <label><strong>{item.num}.</strong> {item.text}</label>
                      <div style={{ marginTop: '12px' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px', fontSize: '0.9rem' }}>
                          <span>{isZh ? '(a) 主动思考和完成任务' : '(a) Proactively thinking and completing tasks'}</span>
                          <span>{isZh ? '(b) 费力理解AI的意图' : '(b) Painstakingly trying to understand AI'}</span>
                        </div>
                        <input
                          type="range"
                          min="0"
                          max="100"
                          value={form.q11_effortDirection || 50}
                          onChange={(e) => handleChange('q11_effortDirection', e.target.value)}
                          style={{ width: '100%' }}
                        />
                        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', color: '#666', marginTop: '4px' }}>
                          <span>0</span>
                          <span>50</span>
                          <span>100</span>
                        </div>
                      </div>
                    </div>
                  )
                }
                
                return (
                <div key={item.id} className="pretest-question">
                    <label><strong>{item.num}.</strong> {item.text}</label>
                  <div className="pretest-scale-options">
                    {[
                        { val: 1, label: isZh ? '1 = 强烈不同意' : '1 = Strongly Disagree' },
                        { val: 2, label: isZh ? '2 = 不同意' : '2 = Disagree' },
                        { val: 3, label: isZh ? '3 = 中立' : '3 = Neutral' },
                        { val: 4, label: isZh ? '4 = 同意' : '4 = Agree' },
                        { val: 5, label: isZh ? '5 = 强烈同意' : '5 = Strongly Agree' }
                    ].map(({ val, label }) => (
                      <label key={val} className="pretest-scale-option">
                        <input
                          type="radio"
                          name={item.id}
                          value={String(val)}
                          checked={form[item.id] === String(val)}
                          onChange={(e) => handleChange(item.id, e.target.value)}
                        />
                        <span>{label}</span>
                      </label>
                    ))}
                  </div>
                </div>
                )
              })}

              <div className="pretest-topic-header">
                <h3>{isZh ? '先验知识' : 'Prior knowledge'}</h3>
                <p className="pretest-topic-intro">
                  {isZh
                    ? '请回答以下关于您学习主题的问题。'
                    : 'Please answer the following questions about your learning topic.'}
                </p>
                <div className="pretest-topic-divider"></div>
              </div>

              <div className="pretest-question">
                <label><strong>{isZh ? '1. 您在Stratux中学习的主题与您之前使用DeepSeek学习的主题相同吗？如果不同，您学习了什么？' : '1. Is the topic you learned in Stratux the same as that you learned using DeepSeek before? If not, what did you learn?'}</strong></label>
                <div className="pretest-options">
                  <label className="pretest-radio-label">
                    <input
                      type="radio"
                      name="q12_sameTopic"
                      value="yes"
                      checked={form.q12_sameTopic === 'yes'}
                      onChange={(e) => handleChange('q12_sameTopic', e.target.value)}
                    />
                    <span>{isZh ? '是' : 'Yes'}</span>
                  </label>
                  <label className="pretest-radio-label">
                    <input
                      type="radio"
                      name="q12_sameTopic"
                      value="no"
                      checked={form.q12_sameTopic === 'no'}
                      onChange={(e) => handleChange('q12_sameTopic', e.target.value)}
                    />
                    <span>{isZh ? '否' : 'No'}</span>
                  </label>
                </div>
                {form.q12_sameTopic === 'no' && (
                  <div style={{ marginTop: '12px' }}>
                    <input
                      type="text"
                      className="pretest-input"
                      placeholder={isZh ? '请说明您学习了什么' : 'Please specify what you learned'}
                      value={form.q12_differentTopic || ''}
                      onChange={(e) => handleChange('q12_differentTopic', e.target.value)}
                    />
                  </div>
                )}
              </div>

              <div className="pretest-question">
                <label><strong>{isZh ? '2. 在本次研究之前，您如何评价您在Stratux中学习的主题的熟悉程度？' : '2. Before this study session, how would you rate your familiarity with the learning topic you learned in Stratux?'}</strong></label>
                <div className="pretest-scale-options">
                  {[
                    { val: 0, label: isZh ? '0 = 没有先验知识' : '0 = No prior knowledge' },
                    { val: 1, label: isZh ? '1 = 听说过但只知道几个基本术语' : '1 = I have heard of the topic but only know a few basic terms' },
                    { val: 2, label: isZh ? '2 = 理解基本概念但无法详细解释' : '2 = I understand the basic concepts but cannot explain them in detail' },
                    { val: 3, label: isZh ? '3 = 可以将基本概念应用到简单示例或任务' : '3 = I can apply the basic concepts to simple examples or tasks' },
                    { val: 4, label: isZh ? '4 = 可以分析相关问题并比较不同方法' : '4 = I can analyze problems related to this topic and compare different approaches' },
                    { val: 5, label: isZh ? '5 = 具有高级知识，可以批判性评估或扩展该主题的想法' : '5 = I have advanced knowledge and can critically evaluate or extend ideas related to this topic' }
                  ].map(({ val, label }) => (
                    <label key={val} className="pretest-scale-option">
                      <input
                        type="radio"
                        name="q13_familiarity"
                        value={String(val)}
                        checked={form.q13_familiarity === String(val)}
                        onChange={(e) => handleChange('q13_familiarity', e.target.value)}
                      />
                      <span>{label}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="pretest-question">
                <label><strong>{isZh ? '3. 在您的观点中，您如何评价这个学习主题的整体难度？' : '3. In your perspective, how would you rate the overall difficulty of this learning topic?'}</strong></label>
                  <div className="pretest-scale-options">
                    {[
                    { val: 1, label: isZh ? '1 = 非常简单' : '1 = Very Easy' },
                    { val: 2, label: isZh ? '2 = 简单' : '2 = Easy' },
                    { val: 3, label: isZh ? '3 = 一般' : '3 = Moderate' },
                    { val: 4, label: isZh ? '4 = 困难' : '4 = Difficult' },
                    { val: 5, label: isZh ? '5 = 非常困难' : '5 = Very Difficult' }
                    ].map(({ val, label }) => (
                      <label key={val} className="pretest-scale-option">
                        <input
                          type="radio"
                        name="q14_difficulty"
                          value={String(val)}
                        checked={form.q14_difficulty === String(val)}
                        onChange={(e) => handleChange('q14_difficulty', e.target.value)}
                        />
                        <span>{label}</span>
                      </label>
                    ))}
                  </div>
                </div>
            </div>
          </section>

          <section className="test-panel pretest-panel pretest-panel-right">
            <div className="test-chat-feed pretest-form">
              <div className="pretest-topic-header">
                <h3>{isZh ? '任务负荷评估（NASA任务负荷指数）' : 'Task Load Assessment (NASA Task Load Index)'}</h3>
                <p className="pretest-topic-intro">
                  {isZh
                    ? '根据您使用Stratux系统的整体体验，请对以下工作负荷维度进行评分。回答采用5点量表（1 = 非常低，5 = 非常高）。'
                    : 'Based on your overall experience using the Stratux system, please rate the following workload dimensions. Responses are measured on a 5-point scale (1 = Very Low, 5 = Very High).'}
                </p>
                <div className="pretest-topic-divider"></div>
              </div>

              {[
                {
                  id: 'q15_mentalEffort',
                  num: 1,
                  text: isZh
                    ? '在使用系统完成学习任务时，所需的心理努力和注意力水平。'
                    : 'While using the system to complete learning tasks, the level of mental effort and attention required.'
                },
                {
                  id: 'q16_physicalEffort',
                  num: 2,
                  text: isZh
                    ? '在使用系统完成学习任务时，所需的身体努力水平，包括操作和姿势调整。'
                    : 'While using the system to complete learning tasks, the level of physical effort required, including operations and posture adjustments.'
                },
                {
                  id: 'q17_timePressure',
                  num: 3,
                  text: isZh
                    ? '在使用系统完成学习任务时，经历的时间压力水平。'
                    : 'While using the system to complete learning tasks, the level of time pressure experienced.'
                },
                {
                  id: 'q18_overallEffort',
                  num: 4,
                  text: isZh
                    ? '在使用系统完成学习任务时，所需的总体努力水平。'
                    : 'While using the system to complete learning tasks, the overall level of effort required.'
                },
                {
                  id: 'q19_satisfaction',
                  num: 5,
                  text: isZh
                    ? '在使用系统完成学习任务时，我对自己的表现感到满意的水平。'
                    : 'While using the system to complete learning tasks, my level of satisfaction with my own performance.'
                },
                {
                  id: 'q20_frustration',
                  num: 6,
                  text: isZh
                    ? '在使用系统完成学习任务时，经历的挫败、紧张或烦躁水平。'
                    : 'While using the system to complete learning tasks, the level of frustration, tension, or irritation experienced.'
                }
              ].map(item => (
                <div key={item.id} className="pretest-question">
                  <label><strong>{item.num}.</strong> {item.text}</label>
                  <div className="pretest-scale-options">
                    {[
                      { val: 1, label: isZh ? '1 = 非常低' : '1 = Very Low' },
                      { val: 2, label: isZh ? '2 = 低' : '2 = Low' },
                      { val: 3, label: isZh ? '3 = 中等' : '3 = Moderate' },
                      { val: 4, label: isZh ? '4 = 高' : '4 = High' },
                      { val: 5, label: isZh ? '5 = 非常高' : '5 = Very High' }
                    ].map(({ val, label }) => (
                      <label key={val} className="pretest-scale-option">
                        <input
                          type="radio"
                          name={item.id}
                          value={String(val)}
                          checked={form[item.id] === String(val)}
                          onChange={(e) => handleChange(item.id, e.target.value)}
                        />
                        <span>{label}</span>
                      </label>
                    ))}
                  </div>
                </div>
              ))}

              <div className="pretest-topic-header">
                <h3>{isZh ? '开放性问题' : 'Open-ended Questions'}</h3>
                <p className="pretest-topic-intro">
                  {isZh
                    ? '请分享您对以下问题的看法。'
                    : 'Please share your thoughts on the following questions.'}
                </p>
                <div className="pretest-topic-divider"></div>
              </div>

              <div className="pretest-question">
                <label htmlFor="q21_mostHelpfulBloom">
                  <strong>{isZh ? '1. 您认为AI辅助学习在哪个Bloom分类层级最有帮助？请解释为什么这个层级对您来说更容易参与。' : '1. Which level of Bloom\'s Taxonomy do you think AI-assisted learning was most helpful for addressing? Please explain why this level was easier for you to engage with.'}</strong>
                </label>
                <textarea
                  id="q21_mostHelpfulBloom"
                  className="pretest-textarea"
                  value={form.q21_mostHelpfulBloom}
                  onChange={(e) => handleChange('q21_mostHelpfulBloom', e.target.value)}
                  rows={4}
                  placeholder={isZh ? '请输入您的回答' : 'Please enter your answer'}
                />
              </div>

              <div className="pretest-question">
                <label htmlFor="q22_leastHelpfulBloom">
                  <strong>{isZh ? '2. 您认为AI辅助学习在哪个Bloom分类层级最没有帮助？请解释您在这个层级遇到的困难。' : '2. Which level of Bloom\'s Taxonomy do you think AI-assisted learning was least helpful for addressing? Please explain the difficulties you encountered at this level.'}</strong>
                </label>
                <textarea
                  id="q22_leastHelpfulBloom"
                  className="pretest-textarea"
                  value={form.q22_leastHelpfulBloom}
                  onChange={(e) => handleChange('q22_leastHelpfulBloom', e.target.value)}
                  rows={4}
                  placeholder={isZh ? '请输入您的回答' : 'Please enter your answer'}
                />
              </div>

              <div className="pretest-question">
                <label htmlFor="q23_mostBeneficialRole">
                  <strong>{isZh ? '3. 您认为哪个AI角色对您的学习最有帮助？这个角色如何进一步改进？' : '3. Which AI role did you find most beneficial for your learning? How could this role be further improved?'}</strong>
                </label>
                <textarea
                  id="q23_mostBeneficialRole"
                  className="pretest-textarea"
                  value={form.q23_mostBeneficialRole}
                  onChange={(e) => handleChange('q23_mostBeneficialRole', e.target.value)}
                  rows={4}
                  placeholder={isZh ? '请输入您的回答' : 'Please enter your answer'}
                />
              </div>

              <div className="pretest-question">
                <label htmlFor="q24_additionalComments">
                  <strong>{isZh ? '4. 您对系统设计或整体学习体验还有其他评论、建议或反馈吗？' : '4. Do you have any additional comments, suggestions, or feedback regarding the system design or your overall learning experience?'}</strong>
                </label>
                <textarea
                  id="q24_additionalComments"
                  className="pretest-textarea"
                  value={form.q24_additionalComments}
                  onChange={(e) => handleChange('q24_additionalComments', e.target.value)}
                  rows={4}
                  placeholder={isZh ? '请输入您的回答' : 'Please enter your answer'}
                />
              </div>
            </div>
          </section>

          {error && <div className="pretest-error">{error}</div>}
        </form>
      </div>
    </div>
  )
}

export default PostTest
